app2/urls.py
from django.conf.urls import url
from app2 import views

app_name = "app2"

urlpatterns=[
    url(r'^$',views.bbm),
    url(r'^login/$',views.login_new,name="login"),
    url(r'^register/$',views.register,name="register"),
    url(r'^adduser/$',views.adduser),
    url(r'^details/$',views.adddetails),
    url(r'^home/$',views.vwdata,name="home"),
    url(r'^verification/$',views.my_change_password),

]

project2/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from app2 import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^',include('app2.urls'))

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/bbm details.html
{% extends 'bbm.html' %}
{% block content %}

<section class="section">
        <div class="container">
            <div>
            <ul class="form-container ff col-sm-3 nav nav-pils nav-stacked side-menu">
                <li class="active">
                    <a href="{% url 'app2:home' %}">Home</a>
                </li>
                <li> <a href="{% url 'app2:login' %}">Login</a></li>
                <li> <a href="{% url 'app2:register' %}">Register</a></li>
                <li> <a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>

        <div class="col-sm-8 register-container form-container">
            <form method="post" enctype="multipart/form-data" >
                {% csrf_token %}
                {% if invalid %}
                <script>alert('Not a valid form');</script>
                {% endif %}
                {% if success %}
                <script>alert('Data Stored Sucessfully');</script>
                {% endif %}


                <h3 class="text-center"> Enter Blood Details </h3>


                <div class="form-group">
                    <label>Blood ID</label>
                    <input type="text" class="form-control" name="bloodid" id="bloodid">
                </div>

                <div class="form-group">
                    <label>Blood Donar Name</label>
                    <input type="text" class="form-control" name="blooddonarname" id="blooddonarname">
                </div>
                <div class="form-group">
                    <label>Blood Type</label>
                    <input type="text" class="form-control" name="bloodtype" id="bloodtype">
                </div>
                <div class="form-group">
                    <label>Blood Cost</label>
                    <input type="text" class="form-control" name="bloodcost" id="bloodcost">
                </div>


                <div class="form-group text-center">
                    <input type="Submit" class="btn-btn primary">
                </div>

            </form>

        </div></div></div>
    </section>







{% endblock content %}

templates/bbm.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>
        {% block contenttitle %}
        BBM
        {% endblock contenttitle %}
    </title>


    <link type ="text/css" rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <link type ="text/css" rel="stylesheet" href="/assets/css/style.css">
    <link type ="text/css" rel="stylesheet" href="/assets/css/a.css">
    <style>
        .white
        {
        background-color:white;
        margin-top:150px;
        }
    </style>
</head>
<body class="lgn-bg">
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><img class="img-responsive" src="/assets/images/bbm32.png"></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'app2:home' %}">Home</a></li>
              <li><a href="{% url 'app2:login' %}">Login</a></li>
              <li><a href="{% url 'app2:register' %}">Registration</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div>
      </div>
</nav>

<div class="row">
    <div class="col-sm-12">
{% block content %}
        {% endblock content %}
    </div>
</div>

<div class="row nw1">
    <h5> </h5>
</div>

</body>
</html>

templates/home1.html
{% extends 'bbm.html' %}
{% block content %}


{% if donardata %}
<div class = "row" >
    <div class="col-sm-2"></div>
    <div class="col-sm-4">
<table border="5px" class="white">
    <tr>
        <td>Blood Code</td>
        <td>Donar Name</td>
        <td>Donar Email</td>
        <td>Donar Conatct No.</td>
        <td>Donar Age</td>
        <td>Donar Image</td>
        <td>Blood Type</td>
    </tr>
{% for i in donardata %}

    <tr>
<td>{{ i.bloodcode }}</td>
<td>{{ i.donarname }}</td>
<td>{{ i.donaremail }}</td>
<td>{{ i.donarcontactno }}</td>
<td>{{ i.donarage }}</td>


        <td><img height="100px" width="100px" src="/media/{{ i.donarimage }}"/></td>
<td>{{ i.bloodtype }}</td>
</tr>

    {% endfor %}
</table>


        {% endif %}
        </div>
</div>
{% endblock content %}

templates/login_bbm.html
{% extends 'bbm.html' %}
{% block content %}

<section class="section dd">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-4 form-container">

                <form method="post">

                     {% csrf_token %}
                    {% if pinvalid %}
                    <script>alert("invalid password");</script>
                    {% endif %}
                    {% if einvalid %}
                    <script>alert("invalid email");</script>
                    {% endif %}
                    <h3 class="text-center"> Log In </h3>
                    <input type="radio" name="role" value="1">Admin
                    <input type="radio" name="role" value="2">Donar
                    <input type="radio" name="role" value="3">Manager
                    <div class="form-group">
                        <label>Email-Id</label>
                        <input type="text" class="form-control" name="email" id="email">
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="text" class="form-control" name="password" id="password">
                    </div>
                    <div class="form-group text-center">

                        <input type="submit" class="btn btn-primary">
                    </div>

                </form>

            </div>

        </div>
    </div>
</section>

{% endblock content %}

templates/nww.html
{% extends 'bbm.html' %}
{% block content %}

 <div class="col-sm-8 register-container form-container">

     <form method="post" enctype="multipart/form-data" >

                {% csrf_token %}
                {% if length_less %}
                <script>alert('password should be 8 characters');</script>
                {% endif %}
                {% if old_p_invalid %}
                <script>alert('old password invalid');</script>
                {% endif %}
                {% if pass_dont_match %}
                <script>alert('password don't match');</script>
                {% endif %}
                {% if success %}
                <script>alert('password change successfully');</script>
                {% endif %}


                <div class="form-group">

                    <label>OTP</label>
                    <input type="text" class="form-control" name="otp" id="otp">
                </div>
                <div class="form-group">
                    <label>Old Password</label>
                    <input type="text" class="form-control" name="oldpassword" id="oldpassword">
                </div>

                <div class="form-group">
                    <label>New Password</label>
                    <input type="text" class="form-control" name="newpassword" id="newpassword">
                </div>

                <div class="form-group">
                    <label>Confirm New Password</label>
                    <input type="text" class="form-control" name="confirmpassword" id="confirmpassword">
                </div>

                 <div class="form-group text-center">
                    <input type="Submit" class="btn-btn primary">
                </div>


    </form>
 </div>

{% endblock content %}

templates/reg_bbm.html
{% extends 'bbm.html' %}
{% block content %}

    <section class="section">
        <div class="container">
            <div>
            <ul class="form-container ff col-sm-3 nav nav-pils nav-stacked side-menu">
                <li class="active">
                    <a href="#">Home</a>
                </li>
                <li> <a href="{% url 'app2:login' %}">Login</a></li>
                <li> <a href="{% url 'app2:register' %}">Register</a></li>
                <li> <a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>

        <div class="col-sm-8 register-container form-container">
            <form method="post" enctype="multipart/form-data" >
                {% csrf_token %}
                {% if invalid %}
                <script>alert('Not a valid form');</script>
                {% endif %}
                {% if success %}
                <script>alert('Data Stored Sucessfully');</script>
                {% endif %}


                <h3 class="text-center"> REGISTER FORM </h3>

                <select name="s1">
                <option value="1">select</option>
                <option value="2">donar</option>


                </select> <br>

                <div class="form-group">
                    <label>Donar Name</label>
                    <input type="text" class="form-control" name="donarname" id="donarname">
                </div>
                <div class="form-group">
                    <label>Donar EmailId</label>
                    <input type="text" class="form-control" name="donaremail" id="donaremail">
                </div>
                <div class="form-group">
                    <label>Donar Password</label>
                    <input type="text" class="form-control" name="donarpassword" id="donarpassword">
                </div>
                <div class="form-group">
                    <label>Donar Contact No.</label>
                    <input type="text" class="form-control" name="donarcontactno" id="donarcontactno">
                </div>
                <div class="form-group">
                    <label>Donar Age</label>
                    <input type="text" class="form-control" name="donarage" id="donarage">
                </div>
                <div class="form-group">
                    <label>Donar Image</label>
                    <input type="file" class="form-control" name="donarimage">
                </div>

                <div class="form-group text-center">
                    <input type="Submit" class="btn-btn primary">
                </div>

            </form>

        </div></div></div>
    </section>


{% endblock content %}

templates/usr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" >
    {% csrf_token %}
    {% if invalid %}
    <script>alert('Not a valid form');</script>
    {% endif %}
    {% if success %}
    <script>alert('Data Stored Sucessfully');</script>
    {% endif %}
    <label>Rolename</label>
    <input type="text" name="rolename" id="rolename"> <br>
    <input type="submit" value="Insert">

</form>
</body>
</html>

templates/wel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
</head>
<body>
Welcome !! You Are Logged In.....
</body>
</html>

templates/wel1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
</head>
<body>
Hi Manager!! You Are Logged In.....
</body>
</html>